services:
  - type: web
    name: multimodal-rag-system
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install torch --index-url https://download.pytorch.org/whl/cpu
      pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app --timeout 200
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
